# Generated by Django 6.0.2 on 2026-03-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
