# Generated by Django 6.0.2 on 2026-03-08 05:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_category_id_alter_menuimage_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
