# Generated by Django 6.0.2 on 2026-03-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menuimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuimage',
            options={'ordering': ['-id']},
        ),
    ]
